/**
 * Story 29.3 — PKCE S256 utilities (RFC 7636).
 *
 * Architecture reference: Epic 29 §4.1, §4.2b, §8.2, AD-65.
 *
 * Pure functions only — no DB, no API route, no network, no persistent storage.
 *
 * Key invariants (architecture §8.2, AD-65):
 * - The verifier is generated by the bridge and held in bridge memory ONLY.
 *   It is NEVER sent in the URL, stored server-side before redemption, or
 *   serialized into any log/event. Only the derived `code_challenge` is sent
 *   in the authorize URL and stored on the enrollment row.
 * - `code_challenge` = base64url( SHA-256( verifier ) ) with padding stripped
 *   (RFC 7636 §4.2).
 * - Verification uses constant-time comparison to avoid timing oracles.
 */
import { createHash, randomBytes, timingSafeEqual } from "node:crypto";

/** Minimum verifier entropy in bytes (RFC 7636 §4.1: 43-128 chars, >= 256-bit). */
const PKCE_VERIFIER_BYTES = 32;

/**
 * Generate a PKCE verifier (RFC 7636 §4.1).
 *
 * Returns a base64url-encoded string (no padding) of 32 random bytes,
 * yielding 43 chars of >= 256-bit entropy. The caller (bridge) holds this
 * in memory and NEVER sends it in a URL or persists it.
 */
export function generatePkceVerifier(): string {
  return randomBytes(PKCE_VERIFIER_BYTES).toString("base64url");
}

/**
 * Compute the S256 `code_challenge` for a verifier (RFC 7636 §4.2).
 *
 * `code_challenge = base64url( SHA-256( verifier ) )` with padding stripped.
 * The result is safe to send in an authorize URL and to store on the
 * enrollment row (`pkce_code_challenge`).
 */
export function computePkceCodeChallengeS256(verifier: string): string {
  return createHash("sha256").update(verifier).digest("base64url");
}

/**
 * Verify a presented PKCE verifier against the stored S256 challenge.
 *
 * Returns `true` only if `base64url(SHA-256(verifier))` equals `storedChallenge`
 * under constant-time comparison. Returns `false` (never throws) for empty
 * inputs, malformed challenges, or length mismatches.
 *
 * Per AD-65 / §8.2: the verifier is never persisted server-side before this
 * check; the bridge holds it in memory and presents it at `/complete`.
 */
export function verifyPkceS256(
  verifier: string,
  storedChallenge: string,
): boolean {
  if (!verifier || !storedChallenge) return false;
  const computed = computePkceCodeChallengeS256(verifier);
  const a = Buffer.from(computed);
  const b = Buffer.from(storedChallenge);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}